#!/bin/bash 
####################################################################################################
###> New x bash -> _aws-ec2-instance.sh  -> Initial creation user => eric => 2019-10-07_10:13:44 ###
####################################################################################################
##[eric - 2024-11-30-11:24:26]#> Creating removal information pull from display information script 
####################################################################################################
#_#>

env_var=$2
query='Reservations[*].Instances[].{
    InstanceId: InstanceId
}'
out=$(aws ec2 describe-instances --filters="Name=tag:environment,Values=$env_var" --query "$query" )
echo  "$out" |awk '{print $3}'
